name: Erinevate Tubade Klubi
favicon: null
layout_spectrum: 0.32226888183504343
typography_spectrum: 0.9169745519757271
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.730449911672622
  lightness: 0.5534968478605151
  saturation: 0.9812770234420896
  rhythmicContrast: 0.758632701355964
purpose: []
