title: Erinevate Tubade Klubi
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.3297491
  brandStrength: 1
  lightness: 0.5053763
  brandColors:
    - '#2e3192'
    - '#818285'
    - '#ffffff'
    - '#d1d2d4'
    - '#c5c6c7'
  rhythmicContrast: 0.5215054
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Erinevate Tubade Klubi
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.29597
layout_spectrum: 0.53334
