name: Erinevate Tubade Klubi
favicon: null
layout_spectrum: 0
typography_spectrum: 0.48512
title: Erinevate Tubade Klubi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#25aae1'
    - '#818285'
    - '#ffffff'
    - '#2e3192'
    - '#000000'
  brandStrength: 0.75
  lightness: 0.6875
  saturation: 0.75
  rhythmicContrast: 1
purpose: []
