name: Erinevate Tubade Klubi
favicon: null
layout_spectrum: 0.23127
typography_spectrum: 0.48512
title: Erinevate Tubade Klubi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dfe8f6'
    - '#a4d7ef'
    - '#b3e3fa'
    - '#ffffff'
    - '#d6ecf8'
  brandStrength: 0.3125
  lightness: 1
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
