name: Erinevate Tubade Klubi
favicon: null
layout_spectrum: 0.24556
typography_spectrum: 0.59915
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
title: Erinevate Tubade Klubi
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#2e3192'
    - '#818285'
    - '#ffffff'
    - '#d1d2d4'
    - '#c5c6c7'
  brandStrength: 0.625
  lightness: 1
  saturation: 0.6875
  rhythmicContrast: 0
purpose: []
